---
title: "Hands on Exercise 5-1"
author: "Sathvika Subramanian"
date: "February 8, 2025"
date-modified: "last-modified"
execute: 
  echo: true
  eval: true
  warning: false
  freeze: true
---

# 1. Creating Ternary Plot with R


# 2. Installing and launching R packages

```{r}
pacman::p_load(plotly, ggtern, tidyverse)
```


# 3. Data Preparation

## 3.1 Importing Data

```{r}
pop_data <- read_csv("data/respopagsex2000to2018_tidy.csv")
```

## 3.2 Preparing the Data

```{r}
agpop_mutated <- pop_data %>%
  mutate('Year' = as.character(Year)) %>%
  spread(AG, Population) %>%
  mutate(YOUNG = rowSums(.[4:8]))%>%
  mutate(ACTIVE = rowSums(.[9:16]))%>%
  mutate(OLD = rowSums(.[17:21]))%>%
  mutate(TOTAL = rowSums(.[22:24]))%>%
  filter(Year == 2018)%>%
  filter(TOTAL > 0)
```


# 4. Plotting Ternary Diagram with R

## 4.1 Plotting a static ternary diagram

```{r}
ggtern(data=agpop_mutated, aes(x=YOUNG, y=ACTIVE, z=OLD)) + geom_point()
```

```{r}
ggtern(data=agpop_mutated, aes(x=YOUNG, y=ACTIVE, z=OLD)) + geom_point() +
  labs(title="Population structure, 2015") +
  theme_rgbw()
```

## 4.2 Plotting an interative ternary diagram

```{r}
# reusable function for creating annotation object
label <- function(txt) {
  list(
    text = txt, 
    x = 0.1, y = 1,
    ax = 0, ay = 0,
    xref = "paper", yref = "paper", 
    align = "center",
    font = list(family = "serif", size = 15, color = "white"),
    bgcolor = "#b3b3b3", bordercolor = "black", borderwidth = 2
  )
}

# reusable function for axis formatting
axis <- function(txt) {
  list(
    title = txt, tickformat = ".0%", tickfont = list(size = 10)
  )
}

ternaryAxes <- list(
  aaxis = axis("Young"), 
  baxis = axis("Active"), 
  caxis = axis("Old")
)

# Initiating a plotly visualization 
plot_ly(
  agpop_mutated, 
  a = ~YOUNG, 
  b = ~ACTIVE, 
  c = ~OLD, 
  color = I("black"), 
  type = "scatterternary"
) %>%
  layout(
    annotations = label("Ternary Markers"), 
    ternary = ternaryAxes
  )
```
