project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left: 
      - text: "Hands-on Exercise"
        menu:
         - text: "Hands-on Exercise 1"
           href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
         - text: "Hands-on Exercise 2"
           href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: sandstone
    backgroundcolor: '#f7d9bc'
    light: cosmo
    toc: true
    smooth-scroll: true
    code-block-bg: true
    code-block-border-left: "#FFA500"
    code-line-numbers: true
    highlight-style: espresso
    code-links:
      - text: GitHub Repo
        icon: file-code
        href: https://github.com/Sathvika-7284/ISSS608-VAA

editor: visual

