project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left: 
      - text: "Hands-on Exercise"
        menu:
         - text: "Hands-on Exercise 1"
           href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
         - text: "Hands-on Exercise 2"
           href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
         - text: "Hands-on Exercise 3-1"
           href: "Hands-on_Ex/Hands-on_Ex3-1/Hands-on_Ex3-1.html"
         - text: "Hands-on Exercise 3-2"
           href: "Hands-on_Ex/Hands-on_Ex3-2/Hands-on_Ex3-2.html"
         - text: "Hands-on Exercise 4-1"
           href: "Hands-on_Ex/Hands-on_Ex4-1/Hands-on_Ex4-1.html"
         - text: "Hands-on Exercise 4-2"
           href: "Hands-on_Ex/Hands-on_Ex4-2/Hands-on_Ex4-2.html"
         - text: "Hands-on Exercise 4-3"
           href: "Hands-on_Ex/Hands-on_Ex4-3/Hands-on_Ex4-3.html"
         - text: "Hands-on Exercise 4-4"
           href: "Hands-on_Ex/Hands-on_Ex4-4/Hands-on_Ex4-4.html"
           
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: sandstone
    backgroundcolor: '#ADD8E6'
    light: cosmo
    toc: true
    smooth-scroll: true
    code-line-numbers: true
    code-block-bg: true
    code-block-border-left: "#FFA500"
    highlight-style: gruvbox
    code-links:
      - text: GitHub Repo
        icon: file-code
        href: https://github.com/Sathvika-7284/ISSS608-VAA

editor: visual

