---
title: "Hands on Exercise 8-2"
author: "Sathvika Subramanian"
date: "March 13, 2025"
date-modified: "last-modified"
execute: 
  echo: true
  eval: true
  warning: false
  freeze: true
---

# Visualising Geospatial Point Data

# 1. Getting Started

```{r}
pacman::p_load(sf, tmap, tidyverse)
```


# 2. Geospatial Data Wrangling

## 2.1 Data Import and Preparation

```{r}
sgpools <- read_csv("data/aspatial/SGPools_svy21.csv")
```

```{r}
list(sgpools) 
```

## 2.2 Creating a sf data frame from an aspatial data frame

```{r}
sgpools_sf <- st_as_sf(sgpools, 
                       coords = c("XCOORD", "YCOORD"),
                       crs= 3414)
```

```{r}
list(sgpools_sf)
```


# 3. Drawing Proportional Symbol Map

```{r}
tmap_mode("view")
```

## 3.1 It all started with an interactive point symbol map

```{r}
tm_shape(sgpools_sf)+
tm_bubbles(col = "red",
           size = 1,
           border.col = "black",
           border.lwd = 1)
```

## 3.2 Lets make it proportional

```{r}
tm_shape(sgpools_sf)+
tm_bubbles(col = "red",
           size = "Gp1Gp2 Winnings",
           border.col = "black",
           border.lwd = 1)
```

## 3.3 Lets give it a different colour

```{r}
tm_shape(sgpools_sf)+
tm_bubbles(col = "OUTLET TYPE", 
          size = "Gp1Gp2 Winnings",
          border.col = "black",
          border.lwd = 1)
```

## 3.4 I have a twin brothers :)

```{r}
tm_shape(sgpools_sf) +
  tm_bubbles(col = "OUTLET TYPE", 
          size = "Gp1Gp2 Winnings",
          border.col = "black",
          border.lwd = 1) +
  tm_facets(by= "OUTLET TYPE",
            nrow = 1,
            sync = TRUE)
```

```{r}
tmap_mode("plot")
```
